const healthcareProducts = [
    {
      "id": 100,
      "name": "Chlorhexidine Baby Care Product 1",
      "price": 210,
      "description": "Baby Care product to support health and well-being.",
      "category": "Baby Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 88,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Adaptogen",
      "indications": "Allergic rhinitis",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 101,
      "name": "Vitamin C Baby Care Product 2",
      "price": 295,
      "description": "Baby Care product to support health and well-being.",
      "category": "Baby Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 78,
      "activeIngredients": "Vitamin C",
      "drugClass": "Antiseptic",
      "indications": "Digestive support",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Himalaya"
    },
    {
      "id": 102,
      "name": "Vitamin E Baby Care Product 3",
      "price": 404,
      "description": "Baby Care product to support health and well-being.",
      "category": "Baby Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 23,
      "activeIngredients": "Vitamin E",
      "drugClass": "Adaptogen",
      "indications": "Joint pain",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 103,
      "name": "Ibuprofen Baby Care Product 4",
      "price": 238,
      "description": "Baby Care product to support health and well-being.",
      "category": "Baby Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 83,
      "activeIngredients": "Ibuprofen",
      "drugClass": "Emollient",
      "indications": "Immunity boost",
      "warnings": "For external use only.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 104,
      "name": "Aloe Vera Baby Care Product 5",
      "price": 312,
      "description": "Baby Care product to support health and well-being.",
      "category": "Baby Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 31,
      "activeIngredients": "Aloe Vera",
      "drugClass": "Adaptogen",
      "indications": "Hair loss",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 105,
      "name": "Vitamin E Baby Care Product 6",
      "price": 284,
      "description": "Baby Care product to support health and well-being.",
      "category": "Baby Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 65,
      "activeIngredients": "Vitamin E",
      "drugClass": "Probiotic",
      "indications": "Immunity boost",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Ayush"
    },
    {
      "id": 106,
      "name": "Aloe Vera Adult Personal Care Product 1",
      "price": 467,
      "description": "Adult Personal Care product to support health and well-being.",
      "category": "Adult Personal Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 86,
      "activeIngredients": "Aloe Vera",
      "drugClass": "Antipyretic",
      "indications": "Stress relief",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Dove"
    },
    {
      "id": 107,
      "name": "Chlorhexidine Adult Personal Care Product 2",
      "price": 269,
      "description": "Adult Personal Care product to support health and well-being.",
      "category": "Adult Personal Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 68,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Herbal Extract",
      "indications": "Joint pain",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 108,
      "name": "Menthol Adult Personal Care Product 3",
      "price": 490,
      "description": "Adult Personal Care product to support health and well-being.",
      "category": "Adult Personal Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 56,
      "activeIngredients": "Menthol",
      "drugClass": "Analgesic",
      "indications": "Hair loss",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 109,
      "name": "Vitamin C Adult Personal Care Product 4",
      "price": 155,
      "description": "Adult Personal Care product to support health and well-being.",
      "category": "Adult Personal Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 60,
      "activeIngredients": "Vitamin C",
      "drugClass": "Emollient",
      "indications": "Dry skin",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Ayush"
    },
    {
      "id": 110,
      "name": "Vitamin C Adult Personal Care Product 5",
      "price": 374,
      "description": "Adult Personal Care product to support health and well-being.",
      "category": "Adult Personal Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 82,
      "activeIngredients": "Vitamin C",
      "drugClass": "Analgesic",
      "indications": "Hair loss",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Himalaya"
    },
    {
      "id": 111,
      "name": "Turmeric Adult Personal Care Product 6",
      "price": 475,
      "description": "Adult Personal Care product to support health and well-being.",
      "category": "Adult Personal Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 75,
      "activeIngredients": "Turmeric",
      "drugClass": "Antipyretic",
      "indications": "Dry skin",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 112,
      "name": "Vitamin E Ayurvedic Products Product 1",
      "price": 315,
      "description": "Ayurvedic Products product to support health and well-being.",
      "category": "Ayurvedic Products",
      "image": "/src/assets/logo.jpeg",
      "stock": 25,
      "activeIngredients": "Vitamin E",
      "drugClass": "Adaptogen",
      "indications": "Digestive support",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 113,
      "name": "Chlorhexidine Ayurvedic Products Product 2",
      "price": 222,
      "description": "Ayurvedic Products product to support health and well-being.",
      "category": "Ayurvedic Products",
      "image": "/src/assets/logo.jpeg",
      "stock": 64,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Antipyretic",
      "indications": "Hair loss",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 114,
      "name": "Vitamin E Ayurvedic Products Product 3",
      "price": 423,
      "description": "Ayurvedic Products product to support health and well-being.",
      "category": "Ayurvedic Products",
      "image": "/src/assets/logo.jpeg",
      "stock": 75,
      "activeIngredients": "Vitamin E",
      "drugClass": "Emollient",
      "indications": "Allergic rhinitis",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 115,
      "name": "Neem Ayurvedic Products Product 4",
      "price": 272,
      "description": "Ayurvedic Products product to support health and well-being.",
      "category": "Ayurvedic Products",
      "image": "/src/assets/logo.jpeg",
      "stock": 80,
      "activeIngredients": "Neem",
      "drugClass": "Analgesic",
      "indications": "Joint pain",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Dove"
    },
    {
      "id": 116,
      "name": "Chlorhexidine Ayurvedic Products Product 5",
      "price": 297,
      "description": "Ayurvedic Products product to support health and well-being.",
      "category": "Ayurvedic Products",
      "image": "/src/assets/logo.jpeg",
      "stock": 87,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Antiseptic",
      "indications": "Digestive support",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Himalaya"
    },
    {
      "id": 117,
      "name": "Menthol Ayurvedic Products Product 6",
      "price": 371,
      "description": "Ayurvedic Products product to support health and well-being.",
      "category": "Ayurvedic Products",
      "image": "/src/assets/logo.jpeg",
      "stock": 20,
      "activeIngredients": "Menthol",
      "drugClass": "Cleanser",
      "indications": "Immunity boost",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Dove"
    },
    {
      "id": 118,
      "name": "Aloe Vera Skin Care Product 1",
      "price": 117,
      "description": "Skin Care product to support health and well-being.",
      "category": "Skin Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 77,
      "activeIngredients": "Aloe Vera",
      "drugClass": "Analgesic",
      "indications": "Allergic rhinitis",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Himalaya"
    },
    {
      "id": 119,
      "name": "Ibuprofen Skin Care Product 2",
      "price": 199,
      "description": "Skin Care product to support health and well-being.",
      "category": "Skin Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 63,
      "activeIngredients": "Ibuprofen",
      "drugClass": "Probiotic",
      "indications": "Digestive support",
      "warnings": "For external use only.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 120,
      "name": "Neem Skin Care Product 3",
      "price": 457,
      "description": "Skin Care product to support health and well-being.",
      "category": "Skin Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 87,
      "activeIngredients": "Neem",
      "drugClass": "Adaptogen",
      "indications": "Allergic rhinitis",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 121,
      "name": "Turmeric Skin Care Product 4",
      "price": 470,
      "description": "Skin Care product to support health and well-being.",
      "category": "Skin Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 68,
      "activeIngredients": "Turmeric",
      "drugClass": "Cleanser",
      "indications": "Immunity boost",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Ayush"
    },
    {
      "id": 122,
      "name": "Menthol Skin Care Product 5",
      "price": 214,
      "description": "Skin Care product to support health and well-being.",
      "category": "Skin Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 85,
      "activeIngredients": "Menthol",
      "drugClass": "Antiseptic",
      "indications": "Joint pain",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 123,
      "name": "Vitamin E Skin Care Product 6",
      "price": 384,
      "description": "Skin Care product to support health and well-being.",
      "category": "Skin Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 28,
      "activeIngredients": "Vitamin E",
      "drugClass": "Antipyretic",
      "indications": "Cough",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Ayush"
    },
    {
      "id": 124,
      "name": "Vitamin C Hair Care Product 1",
      "price": 500,
      "description": "Hair Care product to support health and well-being.",
      "category": "Hair Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 76,
      "activeIngredients": "Vitamin C",
      "drugClass": "Antipyretic",
      "indications": "Joint pain",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 125,
      "name": "Lactobacillus Hair Care Product 2",
      "price": 321,
      "description": "Hair Care product to support health and well-being.",
      "category": "Hair Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 40,
      "activeIngredients": "Lactobacillus",
      "drugClass": "Cleanser",
      "indications": "Fever",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 126,
      "name": "Vitamin C Hair Care Product 3",
      "price": 263,
      "description": "Hair Care product to support health and well-being.",
      "category": "Hair Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 81,
      "activeIngredients": "Vitamin C",
      "drugClass": "Vitamin",
      "indications": "Fever",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Ayush"
    },
    {
      "id": 127,
      "name": "Menthol Hair Care Product 4",
      "price": 201,
      "description": "Hair Care product to support health and well-being.",
      "category": "Hair Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 96,
      "activeIngredients": "Menthol",
      "drugClass": "Cleanser",
      "indications": "Digestive support",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Ayush"
    },
    {
      "id": 128,
      "name": "Vitamin E Hair Care Product 5",
      "price": 240,
      "description": "Hair Care product to support health and well-being.",
      "category": "Hair Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 92,
      "activeIngredients": "Vitamin E",
      "drugClass": "Herbal Extract",
      "indications": "Hair loss",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 129,
      "name": "Aloe Vera Hair Care Product 6",
      "price": 459,
      "description": "Hair Care product to support health and well-being.",
      "category": "Hair Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 44,
      "activeIngredients": "Aloe Vera",
      "drugClass": "Antipyretic",
      "indications": "Stress relief",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Ayush"
    },
    {
      "id": 130,
      "name": "Lactobacillus Vitamins & Supplements Product 1",
      "price": 310,
      "description": "Vitamins & Supplements product to support health and well-being.",
      "category": "Vitamins & Supplements",
      "image": "/src/assets/logo.jpeg",
      "stock": 23,
      "activeIngredients": "Lactobacillus",
      "drugClass": "Herbal Extract",
      "indications": "Immunity boost",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 131,
      "name": "Turmeric Vitamins & Supplements Product 2",
      "price": 255,
      "description": "Vitamins & Supplements product to support health and well-being.",
      "category": "Vitamins & Supplements",
      "image": "/src/assets/logo.jpeg",
      "stock": 20,
      "activeIngredients": "Turmeric",
      "drugClass": "Adaptogen",
      "indications": "Dry skin",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Ayush"
    },
    {
      "id": 132,
      "name": "Chlorhexidine Vitamins & Supplements Product 3",
      "price": 297,
      "description": "Vitamins & Supplements product to support health and well-being.",
      "category": "Vitamins & Supplements",
      "image": "/src/assets/logo.jpeg",
      "stock": 27,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Adaptogen",
      "indications": "Cough",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 133,
      "name": "Vitamin C Vitamins & Supplements Product 4",
      "price": 386,
      "description": "Vitamins & Supplements product to support health and well-being.",
      "category": "Vitamins & Supplements",
      "image": "/src/assets/logo.jpeg",
      "stock": 99,
      "activeIngredients": "Vitamin C",
      "drugClass": "Adaptogen",
      "indications": "Cough",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 134,
      "name": "Lactobacillus Vitamins & Supplements Product 5",
      "price": 329,
      "description": "Vitamins & Supplements product to support health and well-being.",
      "category": "Vitamins & Supplements",
      "image": "/src/assets/logo.jpeg",
      "stock": 81,
      "activeIngredients": "Lactobacillus",
      "drugClass": "Cleanser",
      "indications": "Cough",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Dove"
    },
    {
      "id": 135,
      "name": "Neem Vitamins & Supplements Product 6",
      "price": 318,
      "description": "Vitamins & Supplements product to support health and well-being.",
      "category": "Vitamins & Supplements",
      "image": "/src/assets/logo.jpeg",
      "stock": 27,
      "activeIngredients": "Neem",
      "drugClass": "Antiseptic",
      "indications": "Allergic rhinitis",
      "warnings": "For external use only.",
      "manufacturer": "Ayush"
    },
    {
      "id": 136,
      "name": "Vitamin C First Aid Product 1",
      "price": 144,
      "description": "First Aid product to support health and well-being.",
      "category": "First Aid",
      "image": "/src/assets/logo.jpeg",
      "stock": 98,
      "activeIngredients": "Vitamin C",
      "drugClass": "Antipyretic",
      "indications": "Digestive support",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Himalaya"
    },
    {
      "id": 137,
      "name": "Paracetamol First Aid Product 2",
      "price": 385,
      "description": "First Aid product to support health and well-being.",
      "category": "First Aid",
      "image": "/src/assets/logo.jpeg",
      "stock": 53,
      "activeIngredients": "Paracetamol",
      "drugClass": "Adaptogen",
      "indications": "Immunity boost",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 138,
      "name": "Paracetamol First Aid Product 3",
      "price": 473,
      "description": "First Aid product to support health and well-being.",
      "category": "First Aid",
      "image": "/src/assets/logo.jpeg",
      "stock": 64,
      "activeIngredients": "Paracetamol",
      "drugClass": "Antipyretic",
      "indications": "Hair loss",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 139,
      "name": "Chlorhexidine First Aid Product 4",
      "price": 320,
      "description": "First Aid product to support health and well-being.",
      "category": "First Aid",
      "image": "/src/assets/logo.jpeg",
      "stock": 49,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Emollient",
      "indications": "Immunity boost",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Himalaya"
    },
    {
      "id": 140,
      "name": "Ashwagandha First Aid Product 5",
      "price": 232,
      "description": "First Aid product to support health and well-being.",
      "category": "First Aid",
      "image": "/src/assets/logo.jpeg",
      "stock": 30,
      "activeIngredients": "Ashwagandha",
      "drugClass": "Antiseptic",
      "indications": "Hair loss",
      "warnings": "For external use only.",
      "manufacturer": "Patanjali"
    },
    {
      "id": 141,
      "name": "Menthol First Aid Product 6",
      "price": 156,
      "description": "First Aid product to support health and well-being.",
      "category": "First Aid",
      "image": "/src/assets/logo.jpeg",
      "stock": 63,
      "activeIngredients": "Menthol",
      "drugClass": "Emollient",
      "indications": "Immunity boost",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Ayush"
    },
    {
      "id": 142,
      "name": "Vitamin E Digestive Health Product 1",
      "price": 223,
      "description": "Digestive Health product to support health and well-being.",
      "category": "Digestive Health",
      "image": "/src/assets/logo.jpeg",
      "stock": 37,
      "activeIngredients": "Vitamin E",
      "drugClass": "Vitamin",
      "indications": "Hair loss",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Ayush"
    },
    {
      "id": 143,
      "name": "Lactobacillus Digestive Health Product 2",
      "price": 374,
      "description": "Digestive Health product to support health and well-being.",
      "category": "Digestive Health",
      "image": "/src/assets/logo.jpeg",
      "stock": 64,
      "activeIngredients": "Lactobacillus",
      "drugClass": "Adaptogen",
      "indications": "Digestive support",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 144,
      "name": "Vitamin C Digestive Health Product 3",
      "price": 314,
      "description": "Digestive Health product to support health and well-being.",
      "category": "Digestive Health",
      "image": "/src/assets/logo.jpeg",
      "stock": 41,
      "activeIngredients": "Vitamin C",
      "drugClass": "Emollient",
      "indications": "Fever",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 145,
      "name": "Paracetamol Digestive Health Product 4",
      "price": 266,
      "description": "Digestive Health product to support health and well-being.",
      "category": "Digestive Health",
      "image": "/src/assets/logo.jpeg",
      "stock": 44,
      "activeIngredients": "Paracetamol",
      "drugClass": "Emollient",
      "indications": "Cough",
      "warnings": "For external use only.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 146,
      "name": "Menthol Digestive Health Product 5",
      "price": 146,
      "description": "Digestive Health product to support health and well-being.",
      "category": "Digestive Health",
      "image": "/src/assets/logo.jpeg",
      "stock": 42,
      "activeIngredients": "Menthol",
      "drugClass": "Vitamin",
      "indications": "Fever",
      "warnings": "For external use only.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 147,
      "name": "Ibuprofen Digestive Health Product 6",
      "price": 100,
      "description": "Digestive Health product to support health and well-being.",
      "category": "Digestive Health",
      "image": "/src/assets/logo.jpeg",
      "stock": 51,
      "activeIngredients": "Ibuprofen",
      "drugClass": "Antipyretic",
      "indications": "Dry skin",
      "warnings": "For external use only.",
      "manufacturer": "Ayush"
    },
    {
      "id": 148,
      "name": "Eucalyptus Oil Respiratory Care Product 1",
      "price": 282,
      "description": "Respiratory Care product to support health and well-being.",
      "category": "Respiratory Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 39,
      "activeIngredients": "Eucalyptus Oil",
      "drugClass": "Analgesic",
      "indications": "Allergic rhinitis",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Ayush"
    },
    {
      "id": 149,
      "name": "Turmeric Respiratory Care Product 2",
      "price": 321,
      "description": "Respiratory Care product to support health and well-being.",
      "category": "Respiratory Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 99,
      "activeIngredients": "Turmeric",
      "drugClass": "Antipyretic",
      "indications": "Joint pain",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Dove"
    },
    {
      "id": 150,
      "name": "Vitamin C Respiratory Care Product 3",
      "price": 154,
      "description": "Respiratory Care product to support health and well-being.",
      "category": "Respiratory Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 69,
      "activeIngredients": "Vitamin C",
      "drugClass": "Emollient",
      "indications": "Fever",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Sensodyne"
    },
    {
      "id": 151,
      "name": "Lactobacillus Respiratory Care Product 4",
      "price": 450,
      "description": "Respiratory Care product to support health and well-being.",
      "category": "Respiratory Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 97,
      "activeIngredients": "Lactobacillus",
      "drugClass": "Vitamin",
      "indications": "Hair loss",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 152,
      "name": "Eucalyptus Oil Respiratory Care Product 5",
      "price": 246,
      "description": "Respiratory Care product to support health and well-being.",
      "category": "Respiratory Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 96,
      "activeIngredients": "Eucalyptus Oil",
      "drugClass": "Emollient",
      "indications": "Dry skin",
      "warnings": "For external use only.",
      "manufacturer": "Dove"
    },
    {
      "id": 153,
      "name": "Aloe Vera Respiratory Care Product 6",
      "price": 429,
      "description": "Respiratory Care product to support health and well-being.",
      "category": "Respiratory Care",
      "image": "/src/assets/logo.jpeg",
      "stock": 83,
      "activeIngredients": "Aloe Vera",
      "drugClass": "Emollient",
      "indications": "Stress relief",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Dove"
    },
    {
      "id": 154,
      "name": "Menthol Pain Relief Product 1",
      "price": 469,
      "description": "Pain Relief product to support health and well-being.",
      "category": "Pain Relief",
      "image": "/src/assets/logo.jpeg",
      "stock": 58,
      "activeIngredients": "Menthol",
      "drugClass": "Probiotic",
      "indications": "Fever",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Himalaya"
    },
    {
      "id": 155,
      "name": "Vitamin C Pain Relief Product 2",
      "price": 198,
      "description": "Pain Relief product to support health and well-being.",
      "category": "Pain Relief",
      "image": "/src/assets/logo.jpeg",
      "stock": 92,
      "activeIngredients": "Vitamin C",
      "drugClass": "Emollient",
      "indications": "Cough",
      "warnings": "For external use only.",
      "manufacturer": "Ayush"
    },
    {
      "id": 156,
      "name": "Chlorhexidine Pain Relief Product 3",
      "price": 445,
      "description": "Pain Relief product to support health and well-being.",
      "category": "Pain Relief",
      "image": "/src/assets/logo.jpeg",
      "stock": 99,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Adaptogen",
      "indications": "Joint pain",
      "warnings": "Do not exceed recommended dose.",
      "manufacturer": "Generic Manufacturer"
    },
    {
      "id": 157,
      "name": "Aloe Vera Pain Relief Product 4",
      "price": 256,
      "description": "Pain Relief product to support health and well-being.",
      "category": "Pain Relief",
      "image": "/src/assets/logo.jpeg",
      "stock": 45,
      "activeIngredients": "Aloe Vera",
      "drugClass": "Analgesic",
      "indications": "Digestive support",
      "warnings": "Avoid contact with eyes.",
      "manufacturer": "Patanjali"
    },
    {
      "id": 158,
      "name": "Lactobacillus Pain Relief Product 5",
      "price": 281,
      "description": "Pain Relief product to support health and well-being.",
      "category": "Pain Relief",
      "image": "/src/assets/logo.jpeg",
      "stock": 82,
      "activeIngredients": "Lactobacillus",
      "drugClass": "Emollient",
      "indications": "Immunity boost",
      "warnings": "May cause drowsiness.",
      "manufacturer": "Dove"
    },
    {
      "id": 159,
      "name": "Chlorhexidine Pain Relief Product 6",
      "price": 431,
      "description": "Pain Relief product to support health and well-being.",
      "category": "Pain Relief",
      "image": "/src/assets/logo.jpeg",
      "stock": 24,
      "activeIngredients": "Chlorhexidine",
      "drugClass": "Cleanser",
      "indications": "Wound care",
      "warnings": "Keep out of reach of children.",
      "manufacturer": "Generic Manufacturer"
    }
  ]

  export default healthcareProducts;