const products = [
    // Analgesics
    {
      id: 1,
      name: "Paracetamol",
      price: 50,
      description: "Used to treat fever and mild pain.",
      category: "Analgesic",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Paracetamol",
      drugClass: "Analgesic",
      indications: "Fever, mild to moderate pain",
      warnings: "Do not exceed the recommended dose.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 2,
      name: "Ibuprofen",
      price: 70,
      description: "Nonsteroidal anti-inflammatory drug (NSAID).",
      category: "Analgesic",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Ibuprofen",
      drugClass: "Analgesic",
      indications: "Pain, inflammation, fever",
      warnings: "May cause stomach upset.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 3,
      name: "Aspirin",
      price: 40,
      description: "Used to reduce pain, fever, or inflammation.",
      category: "Analgesic",
      image: "/src/assets/logo.jpeg",
      stock: 120,
      activeIngredients: "Acetylsalicylic Acid",
      drugClass: "Analgesic",
      indications: "Mild to moderate pain, fever",
      warnings: "Not recommended for children.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 4,
      name: "Naproxen",
      price: 60,
      description: "Used to relieve pain and inflammation.",
      category: "Analgesic",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Naproxen",
      drugClass: "Analgesic",
      indications: "Arthritis, muscle pain",
      warnings: "May cause gastrointestinal issues.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 5,
      name: "Diclofenac",
      price: 80,
      description: "Used to treat pain and inflammation.",
      category: "Analgesic",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Diclofenac Sodium",
      drugClass: "Analgesic",
      indications: "Pain, inflammation",
      warnings: "May increase risk of heart attack.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 6,
      name: "Ketorolac",
      price: 90,
      description: "Short-term management of moderate to severe pain.",
      category: "Analgesic",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Ketorolac Tromethamine",
      drugClass: "Analgesic",
      indications: "Post-operative pain",
      warnings: "Not for long-term use.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Antibiotics
    {
      id: 7,
      name: "Amoxicillin",
      price: 55,
      description: "Used to treat various bacterial infections.",
      category: "Antibiotic",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Amoxicillin",
      drugClass: "Antibiotic",
      indications: "Bacterial infections",
      warnings: "Allergic reactions possible.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 8,
      name: "Ciprofloxacin",
      price: 65,
      description: "Used to treat a variety of bacterial infections.",
      category: "Antibiotic",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Ciprofloxacin",
      drugClass: "Antibiotic",
      indications: "Urinary tract infections",
      warnings: "May cause tendon damage.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 9,
      name: "Azithromycin",
      price: 75,
      description: "Used to treat respiratory infections.",
      category: "Antibiotic",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Azithromycin",
      drugClass: "Antibiotic",
      indications: "Respiratory infections",
      warnings: "May cause gastrointestinal upset.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 10,
      name: "Clarithromycin",
      price: 85,
      description: "Used to treat various bacterial infections.",
      category: "Antibiotic",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Clarithromycin",
      drugClass: "Antibiotic",
      indications: "Bacterial infections, respiratory infections",
      warnings: "May interact with other medications.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 11,
      name: "Doxycycline",
      price: 95,
      description: "Used to treat a wide range of infections.",
      category: "Antibiotic",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Doxycycline",
      drugClass: "Antibiotic",
      indications: "Acne, respiratory infections",
      warnings: "Avoid sun exposure.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 12,
      name: "Metronidazole",
      price: 50,
      description: "Used to treat infections caused by bacteria and parasites.",
      category: "Antibiotic",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Metronidazole",
      drugClass: "Antibiotic",
      indications: "Bacterial infections, certain parasitic infections",
      warnings: "Avoid alcohol during treatment.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Antihistamines
    {
      id: 13,
      name: "Loratadine",
      price: 30,
      description: "Used to relieve allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 120,
      activeIngredients: "Loratadine",
      drugClass: "Antihistamine",
      indications: "Allergic rhinitis, hives",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 14,
      name: "Cetirizine",
      price: 35,
      description: "Used to treat allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 110,
      activeIngredients: "Cetirizine",
      drugClass: "Antihistamine",
      indications: "Allergic rhinitis, hives",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 15,
      name: "Diphenhydramine",
      price: 25,
      description: "Used to relieve symptoms of allergy, hay fever, and the common cold.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 130,
      activeIngredients: "Diphenhydramine",
      drugClass: "Antihistamine",
      indications: "Allergy symptoms, insomnia",
      warnings: "May cause significant drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 16,
      name: "Fexofenadine",
      price: 40,
      description: "Used to relieve allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Fexofenadine",
      drugClass: "Antihistamine",
      indications: "Seasonal allergies",
      warnings: "Non-drowsy formula.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 17,
      name: "Chlorpheniramine",
      price: 20,
      description: "Used to relieve allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 140,
      activeIngredients: "Chlorpheniramine",
      drugClass: "Antihistamine",
      indications: "Allergic rhinitis",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 18,
      name: "Desloratadine",
      price: 45,
      description: "Used to relieve allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Desloratadine",
      drugClass: "Antihistamine",
      indications: "Allergic rhinitis",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
  
   {
      id: 19,
      name: "Omeprazole",
      price: 55,
      description: "Used to treat gastroesophageal reflux disease (GERD).",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Omeprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "GERD, stomach ulcers",
      warnings: "Long-term use may lead to vitamin B12 deficiency.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 20,
      name: "Esomeprazole",
      price: 65,
      description: "Used to treat acid reflux and stomach ulcers.",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Esomeprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "GERD, Zollinger-Ellison syndrome",
      warnings: "May increase risk of Clostridium difficile infection.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 21,
      name: "Lansoprazole",
      price: 75,
      description: "Used to treat stomach ulcers and GERD.",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Lansoprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "Stomach ulcers, GERD",
      warnings: "May cause headache or diarrhea.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 22,
      name: "Rabeprazole",
      price: 85,
      description: "Used to treat GERD and other conditions caused by excess stomach acid.",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Rabeprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "GERD, stomach ulcers",
      warnings: "May cause nausea or vomiting.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 23,
      name: "Pantoprazole",
      price: 90,
      description: "Used to treat erosive esophagitis caused by GERD.",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Pantoprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "GERD, Zollinger-Ellison syndrome",
      warnings: "Long-term use may lead to kidney issues.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 24,
      name: "Dexlansoprazole",
      price: 95,
      description: "Used to treat heartburn and other symptoms of GERD.",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Dexlansoprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "GERD, erosive esophagitis",
      warnings: "May cause abdominal pain.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Antidepressants
    {
      id: 25,
      name: "Fluoxetine",
      price: 60,
      description: "Used to treat depression, OCD, and panic disorder.",
      category: "Antidepressant",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Fluoxetine",
      drugClass: "SSRI",
      indications: "Depression, anxiety disorders",
      warnings: "May increase suicidal thoughts in young adults.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 26,
      name: "Sertraline",
      price: 70,
      description: "Used to treat depression and anxiety disorders.",
      category: "Antidepressant",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Sertraline",
      drugClass: "SSRI",
      indications: "Depression, panic disorder",
      warnings: "May cause sexual dysfunction.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 27,
      name: "Citalopram",
      price: 80,
      description: "Used to treat depression.",
      category: "Antidepressant",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Citalopram",
      drugClass: "SSRI",
      indications: "Depression",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 28,
      name: "Escitalopram",
      price: 90,
      description: "Used to treat generalized anxiety disorder and depression.",
      category: "Antidepressant",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Escitalopram",
      drugClass: "SSRI",
      indications: "Depression, anxiety",
      warnings: "May increase risk of serotonin syndrome.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 29,
      name: "Venlafaxine",
      price: 100,
      description: "Used to treat major depressive disorder and anxiety.",
      category: "Antidepressant",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Venlafaxine",
      drugClass: "SNRI",
      indications: "Depression, anxiety disorders",
      warnings: "May cause increased blood pressure.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 30,
      name: "Duloxetine",
      price: 110,
      description: "Used to treat depression, anxiety, and pain disorders.",
      category: "Antidepressant",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Duloxetine",
      drugClass: "SNRI",
      indications: "Depression, chronic pain",
      warnings: "May cause liver damage.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 31,
      name: "Metformin",
      price: 40,
      description: "Used to control blood sugar levels in type 2 diabetes.",
      category: "Antidiabetic",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Metformin",
      drugClass: "Biguanide",
      indications: "Type 2 diabetes",
      warnings: "May cause gastrointestinal upset.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 32,
      name: "Glipizide",
      price: 50,
      description: "Used to control blood sugar levels in type 2 diabetes.",
      category: "Antidiabetic",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Glipizide",
      drugClass: "Sulfonylurea",
      indications: "Type 2 diabetes",
      warnings: "May cause hypoglycemia.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 33,
      name: "Glyburide",
      price: 60,
      description: "Used to control blood sugar levels in type 2 diabetes.",
      category: "Antidiabetic",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Glyburide",
      drugClass: "Sulfonylurea",
      indications: "Type 2 diabetes",
      warnings: "May cause weight gain.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 34,
      name: "Sitagliptin",
      price: 70,
      description: "Used to control blood sugar levels in type 2 diabetes.",
      category: "Antidiabetic",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Sitagliptin",
      drugClass: "DPP-4 Inhibitor",
      indications: "Type 2 diabetes",
      warnings: "May cause pancreatitis.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 35,
      name: "Liraglutide",
      price: 80,
      description: "Used to control blood sugar levels in type 2 diabetes.",
      category: "Antidiabetic",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Liraglutide",
      drugClass: "GLP-1 Agonist",
      indications: "Type 2 diabetes",
      warnings: "May cause nausea.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 36,
      name: "Canagliflozin",
      price: 90,
      description: "Used to control blood sugar levels in type 2 diabetes.",
      category: "Antidiabetic",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Canagliflozin",
      drugClass: "SGLT2 Inhibitor",
      indications: "Type 2 diabetes",
      warnings: "May increase risk of urinary tract infections.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 37,
      name: "Amlodipine",
      price: 45,
      description: "Used to treat high blood pressure and chest pain.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Amlodipine",
      drugClass: "Calcium Channel Blocker",
      indications: "Hypertension, angina",
      warnings: "May cause swelling of the ankles.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 38,
      name: "Lisinopril",
      price: 55,
      description: "Used to treat high blood pressure and heart failure.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Lisinopril",
      drugClass: "ACE Inhibitor",
      indications: "Hypertension, heart failure",
      warnings: "May cause a persistent cough.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 39,
      name: "Losartan",
      price: 65,
      description: "Used to treat high blood pressure and protect the kidneys.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Losartan",
      drugClass: "Angiotensin II Receptor Blocker",
      indications: "Hypertension, diabetic nephropathy",
      warnings: "May cause dizziness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 40,
      name: "Hydrochlorothiazide",
      price: 35,
      description: "Used to treat high blood pressure and fluid retention.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 110,
      activeIngredients: "Hydrochlorothiazide",
      drugClass: "Thiazide Diuretic",
      indications: "Hypertension, edema",
      warnings: "May cause electrolyte imbalance.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 41,
      name: "Metoprolol",
      price: 75,
      description: "Used to treat high blood pressure and heart conditions.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Metoprolol",
      drugClass: "Beta Blocker",
      indications: "Hypertension, angina",
      warnings: "May cause fatigue.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 42,
      name: "Diltiazem",
      price: 85,
      description: "Used to treat high blood pressure and angina.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Diltiazem",
      drugClass: "Calcium Channel Blocker",
      indications: "Hypertension, angina",
      warnings: "May cause dizziness.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 43,
      name: "Atorvastatin",
      price: 50,
      description: "Used to lower cholesterol and triglyceride levels.",
      category: "Antilipemic",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Atorvastatin",
      drugClass: "Statin",
      indications: "High cholesterol",
      warnings: "May cause muscle pain.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 44,
      name: "Simvastatin",
      price: 60,
      description: "Used to lower cholesterol levels.",
      category: "Antilipemic",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Simvastatin",
      drugClass: "Statin",
      indications: "High cholesterol",
      warnings: "May increase risk of liver damage.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 45,
      name: "Rosuvastatin",
      price: 70,
      description: "Used to lower cholesterol and triglyceride levels.",
      category: "Antilipemic",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Rosuvastatin",
      drugClass: "Statin",
      indications: "High cholesterol",
      warnings: "May cause muscle weakness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 46,
      name: "Fenofibrate",
      price: 80,
      description: "Used to lower cholesterol and triglyceride levels.",
      category: "Antilipemic",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Fenofibrate",
      drugClass: "Fibrate",
      indications: "High cholesterol, high triglycerides",
      warnings: "May cause liver issues.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 47,
      name: "Niacin",
      price: 90,
      description: "Used to lower cholesterol levels.",
      category: "Antilipemic",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Niacin",
      drugClass: "Vitamin B3",
      indications: "High cholesterol",
      warnings: "May cause flushing.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 48,
      name: "Ezetimibe",
      price: 100,
      description: "Used to lower cholesterol levels.",
      category: "Antilipemic",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Ezetimibe",
      drugClass: "Cholesterol Absorption Inhibitor",
      indications: "High cholesterol",
      warnings: "May cause muscle pain.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 49,
      name: "Levothyroxine",
      price: 40,
      description: "Used to treat hypothyroidism.",
      category: "Thyroid Hormone",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Levothyroxine",
      drugClass: "Thyroid Hormone",
      indications: "Hypothyroidism",
      warnings: "May cause increased heart rate.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 50,
      name: "Liothyronine",
      price: 50,
      description: "Used to treat hypothyroidism.",
      category: "Thyroid Hormone",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Liothyronine",
      drugClass: "Thyroid Hormone",
      indications: "Hypothyroidism",
      warnings: "May cause anxiety.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 51,
      name: "Methimazole",
      price: 60,
      description: "Used to treat hyperthyroidism.",
      category: "Thyroid Hormone",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Methimazole",
      drugClass: "Thyroid Hormone",
      indications: "Hyperthyroidism",
      warnings: "May cause liver issues.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 52,
      name: "Propylthiouracil",
      price: 70,
      description: "Used to treat hyperthyroidism.",
      category: "Thyroid Hormone",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Propylthiouracil",
      drugClass: "Thyroid Hormone",
      indications: "Hyperthyroidism",
      warnings: "May cause rash.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 53,
      name: "Iodine-131",
      price: 80,
      description: "Used to treat hyperthyroidism and thyroid cancer.",
      category: "Thyroid Hormone",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Iodine-131",
      drugClass: "Radioactive Isotope",
      indications: "Hyperthyroidism, thyroid cancer",
      warnings: "May cause radiation exposure.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 54,
      name: "Thyroid USP",
      price: 90,
      description: "Used to treat hypothyroidism.",
      category: "Thyroid Hormone",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Thyroid Extract",
      drugClass: "Thyroid Hormone",
      indications: "Hypothyroidism",
      warnings: "May cause allergic reactions.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 55,
      name: "Albuterol",
      price: 30,
      description: "Used to treat asthma and COPD.",
      category: "Bronchodilator",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Albuterol",
      drugClass: "Beta-2 Agonist",
   indications: "Asthma, COPD",
      warnings: "May cause increased heart rate.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 56,
      name: "Salmeterol",
      price: 40,
      description: "Used to prevent asthma attacks and treat COPD.",
      category: "Bronchodilator",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Salmeterol",
      drugClass: "Beta-2 Agonist",
      indications: "Asthma, COPD",
      warnings: "Not for acute attacks.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 57,
      name: "Formoterol",
      price: 50,
      description: "Used to treat asthma and COPD.",
      category: "Bronchodilator",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Formoterol",
      drugClass: "Beta-2 Agonist",
      indications: "Asthma, COPD",
      warnings: "May cause palpitations.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 58,
      name: "Ipratropium",
      price: 60,
      description: "Used to relieve bronchospasm in COPD.",
      category: "Bronchodilator",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Ipratropium Bromide",
      drugClass: "Anticholinergic",
      indications: "COPD",
      warnings: "May cause dry mouth.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 59,
      name: "Tiotropium",
      price: 70,
      description: "Used to prevent bronchospasm in COPD.",
      category: "Bronchodilator",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Tiotropium",
      drugClass: "Anticholinergic",
      indications: "COPD",
      warnings: "May cause constipation.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 60,
      name: "Theophylline",
      price: 80,
      description: "Used to treat asthma and COPD.",
      category: "Bronchodilator",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Theophylline",
      drugClass: "Methylxanthine",
      indications: "Asthma, COPD",
      warnings: "May cause nausea.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 61,
      name: "Prednisone",
      price: 30,
      description: "Used to treat inflammatory conditions.",
      category: "Corticosteroid",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Prednisone",
      drugClass: "Corticosteroid",
      indications: "Inflammation, allergies",
      warnings: "May cause weight gain.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 62,
      name: "Hydrocortisone",
      price: 40,
      description: "Used to treat inflammation and adrenal insufficiency.",
      category: "Corticosteroid",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Hydrocortisone",
      drugClass: "Corticosteroid",
      indications: "Inflammation, adrenal insufficiency",
      warnings: "May cause mood changes.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 63,
      name: "Dexamethasone",
      price: 50,
      description: "Used to treat severe allergies and inflammation.",
      category: "Corticosteroid",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Dexamethasone",
      drugClass: "Corticosteroid",
      indications: "Severe allergies, inflammation",
      warnings: "May cause insomnia.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 64,
      name: "Methylprednisolone",
      price: 60,
      description: "Used to treat inflammation and autoimmune conditions.",
      category: "Corticosteroid",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Methylprednisolone",
      drugClass: "Corticosteroid",
      indications: "Inflammation, autoimmune conditions",
      warnings: "May cause increased appetite.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 65,
      name: "Betamethasone",
      price: 70,
      description: "Used to treat various inflammatory conditions.",
      category: "Corticosteroid",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Betamethasone",
      drugClass: "Corticosteroid",
      indications: "Inflammation, skin conditions",
      warnings: "May cause skin thinning.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 66,
      name: "Fluticasone",
      price: 80,
      description: "Used to treat allergic rhinitis and asthma.",
      category: "Corticosteroid",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Fluticasone",
      drugClass: "Corticosteroid",
      indications: "Allergic rhinitis, asthma",
      warnings: "May cause nasal irritation.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 67,
      name: "Ranitidine",
      price: 30,
      description: "Used to treat stomach ulcers and GERD.",
      category: "H2 Antagonist",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Ranitidine",
      drugClass: "H2 Antagonist",
      indications: "Stomach ulcers, GERD",
      warnings: "May cause dizziness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 68,
      name: "Famotidine",
      price: 40,
      description: "Used to treat ulcers and GERD.",
      category: "H2 Antagonist",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Famotidine",
      drugClass: "H2 Antagonist",
      indications: "Stomach ulcers, GERD",
      warnings: "May cause headache.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 69,
      name: "Cimetidine",
      price: 50,
      description: "Used to treat ulcers and GERD.",
      category: "H2 Antagonist",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Cimetidine",
      drugClass: "H2 Antagonist",
      indications: "Stomach ulcers, GERD",
      warnings: "May interact with other medications.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 70,
      name: "Nizatidine",
      price: 60,
      description: "Used to treat ulcers and GERD.",
      category: "H2 Antagonist",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Nizatidine",
      drugClass: "H2 Antagonist",
      indications: "Stomach ulcers, GERD",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 71,
      name: "Dexlansoprazole",
      price: 70,
      description: "Used to treat GERD and erosive esophagitis.",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Dexlansoprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "GERD, erosive esophagitis",
      warnings: "May cause abdominal pain.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 72,
      name: "Rabeprazole",
      price: 80,
      description: "Used to treat GERD and other conditions caused by excess stomach acid.",
      category: "Proton Pump Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Rabeprazole",
      drugClass: "Proton Pump Inhibitor",
      indications: "GERD, stomach ulcers",
      warnings: "May cause nausea or vomiting.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 73,
      name: "Atenolol",
      price: 40,
      description: "Used to treat high blood pressure and chest pain.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Atenolol",
      drugClass: "Beta Blocker",
      indications: "Hypertension, angina",
      warnings: "May cause fatigue.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 74,
      name: "Propranolol",
      price: 50,
      description: "Used to treat high blood pressure, anxiety, and migraines.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Propranolol",
      drugClass: "Beta Blocker",
      indications: "Hypertension, anxiety, migraine prevention",
      warnings: "May cause fatigue and dizziness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 75,
      name: "Carvedilol",
      price: 60,
      description: "Used to treat heart failure and high blood pressure.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Carvedilol",
      drugClass: "Beta Blocker",
      indications: "Heart failure, hypertension",
      warnings: "May cause low blood pressure.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 76,
      name: "Bisoprolol",
      price: 70,
      description: "Used to treat high blood pressure and heart failure.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Bisoprolol",
      drugClass: "Beta Blocker",
      indications: "Hypertension, heart failure",
      warnings: "May cause fatigue.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 77,
      name: "Nebivolol",
      price: 80,
      description: "Used to treat high blood pressure.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Nebivolol",
      drugClass: "Beta Blocker",
      indications: "Hypertension",
      warnings: "May cause headache.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 78,
      name: "Doxazosin",
      price: 90,
      description: "Used to treat high blood pressure and symptoms of BPH.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Doxazosin",
      drugClass: "Alpha Blocker",
      indications: "Hypertension, BPH",
      warnings: "May cause dizziness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 79,
      name: "Terazosin",
      price: 100,
      description: "Used to treat high blood pressure and symptoms of BPH.",
      category: "Antihypertensive",
      image: "/src/assets/logo.jpeg",
      stock: 40,
      activeIngredients: "Terazosin",
      drugClass: "Alpha Blocker",
      indications: "Hypertension, BPH",
      warnings: "May cause fainting.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 80,
      name: "Clopidogrel",
      price: 50,
      description: "Used to prevent blood clots.",
      category: "Antiplatelet",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Clopidogrel",
      drugClass: "Antiplatelet",
      indications: "Prevent heart attack, stroke",
      warnings: "May cause bleeding.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 81,
      name: "Aspirin",
      price: 30,
      description: "Used to reduce the risk of heart attack and stroke.",
      category: "Antiplatelet",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Acetylsalicylic Acid",
      drugClass: "Antiplatelet",
      indications: "Prevent heart attack, stroke",
      warnings: "May cause gastrointestinal bleeding.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 82,
      name: "Dipyridamole",
      price: 40,
      description: "Used to prevent blood clots.",
      category: "Antiplatelet",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Dipyridamole",
      drugClass: "Antiplatelet",
      indications: "Prevent blood clots",
      warnings: "May cause headache.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 83,
      name: "Ticagrelor",
      price: 60,
      description: "Used to prevent blood clots in patients with heart disease.",
      category: "Antiplatelet",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Ticagrelor",
      drugClass: "Antiplatelet",
      indications: "Prevent heart attack, stroke",
      warnings: "May cause bleeding.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 84,
      name: "Prasugrel",
      price: 80,
      description: "Used to prevent blood clots in patients with heart disease.",
      category: "Antiplatelet",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Prasugrel",
      drugClass: "Antiplatelet",
      indications: "Prevent heart attack, stroke",
      warnings: "May cause bleeding.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 85,
      name: "Abciximab",
      price: 90,
      description: "Used to prevent blood clots during heart procedures.",
      category: "Antiplatelet",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Abciximab",
      drugClass: "Antiplatelet",
      indications: "Prevent blood clots during PCI",
      warnings: "May cause bleeding.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 86,
      name: "Insulin Glargine",
      price: 100,
      description: "Long-acting insulin used to control blood sugar.",
      category: "Insulin",
      image: "/src/assets/logo.jpeg",
      stock: 100,
      activeIngredients: "Insulin Glargine",
      drugClass: "Insulin",
      indications: "Type 1 and Type 2 diabetes",
      warnings: "May cause hypoglycemia.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 87,
      name: "Insulin Aspart",
      price: 110,
      description: "Rapid-acting insulin used to control blood sugar.",
      category: "Insulin",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Insulin Aspart",
      drugClass: "Insulin",
      indications: "Type 1 and Type 2 diabetes",
      warnings: "May cause hypoglycemia.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 88,
      name: "Insulin Lispro",
      price: 120,
      description: "Rapid-acting insulin used to control blood sugar.",
      category: "Insulin",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Insulin Lispro",
      drugClass: "Insulin",
      indications: "Type 1 and Type 2 diabetes",
      warnings: "May cause hypoglycemia.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 89,
      name: "Insulin Detemir",
      price: 130,
      description: "Long-acting insulin used to control blood sugar.",
      category: "Insulin",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Insulin Detemir",
      drugClass: "Insulin",
      indications: "Type 1 and Type 2 diabetes",
      warnings: "May cause hypoglycemia.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 90,
      name: "Insulin Regular",
      price: 140,
      description: "Short-acting insulin used to control blood sugar.",
      category: "Insulin",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Insulin Regular",
      drugClass: "Insulin",
      indications: "Type 1 and Type 2 diabetes",
      warnings: "May cause hypoglycemia.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 91,
      name: "Insulin NPH",
      price: 150,
      description: "Intermediate-acting insulin used to control blood sugar.",
      category: "Insulin",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Insulin NPH",
      drugClass: "Insulin",
      indications: "Type 1 and Type 2 diabetes",
      warnings: "May cause hypoglycemia.",
      manufacturer: "Generic Manufacturer",
    },
  
    // Continue adding more categories and products up to 100 ids
    {
      id: 92,
      name: "Montelukast",
      price: 30,
      description: "Used to prevent asthma attacks and relieve symptoms of seasonal allergies.",
      category: "Leukotriene Receptor Antagonist",
      image: "/src/assets/logo.jpeg",
      stock:  100,
      activeIngredients: "Montelukast",
      drugClass: "Leukotriene Receptor Antagonist",
      indications: "Asthma, allergic rhinitis",
      warnings: "May cause mood changes.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 93,
      name: "Zafirlukast",
      price: 40,
      description: "Used to prevent asthma attacks.",
      category: "Leukotriene Receptor Antagonist",
      image: "/src/assets/logo.jpeg",
      stock: 90,
      activeIngredients: "Zafirlukast",
      drugClass: "Leukotriene Receptor Antagonist",
      indications: "Asthma",
      warnings: "May cause liver issues.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 94,
      name: "Pranlukast",
      price: 50,
      description: "Used to prevent asthma attacks.",
      category: "Leukotriene Receptor Antagonist",
      image: "/src/assets/logo.jpeg",
      stock: 80,
      activeIngredients: "Pranlukast",
      drugClass: "Leukotriene Receptor Antagonist",
      indications: "Asthma",
      warnings: "May cause headache.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 95,
      name: "Roflumilast",
      price: 60,
      description: "Used to prevent flare-ups of COPD.",
      category: "Phosphodiesterase-4 Inhibitor",
      image: "/src/assets/logo.jpeg",
      stock: 70,
      activeIngredients: "Roflumilast",
      drugClass: "Phosphodiesterase-4 Inhibitor",
      indications: "COPD",
      warnings: "May cause weight loss.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 96,
      name: "Theophylline",
      price: 70,
      description: "Used to treat asthma and COPD.",
      category: "Methylxanthine",
      image: "/src/assets/logo.jpeg",
      stock: 60,
      activeIngredients: "Theophylline",
      drugClass: "Methylxanthine",
      indications: "Asthma, COPD",
      warnings: "May cause nausea.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 97,
      name: "Brompheniramine",
      price: 80,
      description: "Used to relieve allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 50,
      activeIngredients: "Brompheniramine",
      drugClass: "Antihistamine",
      indications: "Allergic rhinitis",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 98,
      name: "Chlorpheniramine",
      price: 90,
      description: "Used to relieve allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 40,
      activeIngredients: "Chlorpheniramine",
      drugClass: "Antihistamine",
      indications: "Allergic rhinitis",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
    {
      id: 99,
      name: "Levocetirizine",
      price: 100,
      description: "Used to relieve allergy symptoms.",
      category: "Antihistamine",
      image: "/src/assets/logo.jpeg",
      stock: 30,
      activeIngredients: "Levocetirizine",
      drugClass: "Antihistamine",
      indications: "Allergic rhinitis",
      warnings: "May cause drowsiness.",
      manufacturer: "Generic Manufacturer",
    },
  ];
export default products;
